[package]
name = "velum"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = { version = "0.8", default-features = false, features = ["simd"] }
handlebars = { git = "https://github.com/sunng87/handlebars-rust.git" }
serde_json = { version = "1.0" }
